### PR TITLE
Extend MSVC version detection range. Due to MSVC Toolset Minor Version Number 14.40 in VS 2022 v17.10.

### PR DESCRIPTION
**Pull request by tatsuya-shiozawa**
## This PR has same reason of https://github.com/Live2D/CubismNativeSamples/pull/46

**Please reference above url for knowind the detail**

### CODE REVIEW

**Comment by wada-at-live2d-com** [comment]
@tatsuya-shiozawa 

Thank you for your contribution.
MotionSync Plugin should also be updated to support the latest MSVC, just like the SDK for Native. 
To document this in the CHANGELOG, please address it in the same manner as the following comment for the SDK for Native.

https://github.com/Live2D/CubismNativeSamples/pull/46#issuecomment-2190488814

**Comment by tatsuya-shiozawa** [comment]
@wada-at-live2d-com 

Thak you for your review.
I added the commit that you shown.

**Review by wada-at-live2d-com — APPROVED** [review]

**Comment by wada-at-live2d-com** [comment]
@tatsuya-shiozawa 

Thank you for your support!
I have confirmed the addition, so I will proceed with the merge.

**Comment by tatsuya-shiozawa** [comment]
Thanks!

**Pull request merged**
